/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useContext, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import Context from "../providers/ContextProvider.provider";
import { useLoader } from "@react-three/fiber";
import { IMAGE_SETTINGS } from "@/lib/constants/generator";

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh;
    Screen: THREE.Mesh;
    Reciever: THREE.Mesh;
    Glass: THREE.Mesh;
  };
  materials: {
    Body: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
    Glas: THREE.MeshPhysicalMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/tv.gltf") as GLTFResult;

  const { model } = useContext(Context);

  const texture = useLoader(THREE.TextureLoader, model.image.src);

  /* SCREEN MOCKUP */
  const image = model.image;

  //   @ts-ignore
  texture.center.set(0.5, 0.5);

  //   @ts-ignore
  texture.rotation = Math.PI / 180;

  //   @ts-ignore
  texture.repeat.set(
    -3 + image.width / IMAGE_SETTINGS.dimensionDivider,
    2.5 + image.height / IMAGE_SETTINGS.dimensionDivider
  );

  //   @ts-ignore
  texture.offset.set(
    0.75 + image.x / IMAGE_SETTINGS.positionDivider,
    0.35 + image.y / IMAGE_SETTINGS.positionDivider
  );
  return (
    <group
      {...props}
      rotation={[-model.position.y, model.position.x, 0]}
      dispose={null}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials.Body}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial
          roughness={model.bodyReflection}
          color={model.color}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={materials.Screen}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial
          attach="material"
          // @ts-ignore
          map={texture}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Reciever.geometry}
        material={materials.Body}
        position={[0, -0.3, 0]}
      />
      {model.screenReflection && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glass.geometry}
          material={materials.Glas}
          rotation={[Math.PI / 2, 0, 0]}
        />
      )}
    </group>
  );
}

useGLTF.preload("/models/tv.gltf");
