import * as THREE from "three";
import { GLTF } from "three-stdlib";

export type AndroidType = GLTF & {
  nodes: {
    AF_Sensor_Glass: THREE.Mesh;
    Antenna_Plastic: THREE.Mesh;
    Back_Cam_Deco: THREE.Mesh;
    Back_Cam_Deco_Black: THREE.Mesh;
    Back_Cover_Glass: THREE.Mesh;
    Bezel: THREE.Mesh;
    Cam_Bezel: THREE.Mesh;
    Cam_Body: THREE.Mesh;
    Cam_Glass: THREE.Mesh;
    Cam_Lens: THREE.Mesh;
    Cam_Mt: THREE.Mesh;
    Display_ActiveArea: THREE.Mesh;
    Flash: THREE.Mesh;
    Flash_Glass: THREE.Mesh;
    Rear_Case: THREE.Mesh;
    Rearcase_Hole: THREE.Mesh;
    S_Pen_Tip: THREE.Mesh;
    Samsung_Logo: THREE.Mesh;
    Usb_1: THREE.Mesh;
    Usb_2: THREE.Mesh;
    Zoom_Cam: THREE.Mesh;
    Display_ActiveArea001: THREE.Mesh;
  };
  materials: {
    AF_Sensor_Glass: THREE.MeshStandardMaterial;
    Antenna_Plastic: THREE.MeshStandardMaterial;
    Back_Cam_Deco: THREE.MeshStandardMaterial;
    Back_Cam_Deco_Black: THREE.MeshStandardMaterial;
    Back_Cover_Glass: THREE.MeshStandardMaterial;
    Bezel: THREE.MeshStandardMaterial;
    Cam_Bezel: THREE.MeshStandardMaterial;
    Cam_Body: THREE.MeshStandardMaterial;
    Cam_Glass: THREE.MeshStandardMaterial;
    Cam_Lens: THREE.MeshStandardMaterial;
    Black_Hole: THREE.MeshStandardMaterial;
    main_glass: THREE.MeshPhysicalMaterial;
    Flash: THREE.MeshStandardMaterial;
    Flash_Glass: THREE.MeshStandardMaterial;
    Rearcase: THREE.MeshStandardMaterial;
    Rearcase_Hole: THREE.MeshStandardMaterial;
    Samsung_Logo: THREE.MeshStandardMaterial;
    Usb_1: THREE.MeshStandardMaterial;
    Usb_2: THREE.MeshStandardMaterial;
    Zoom_Cam: THREE.MeshStandardMaterial;
    ["main_screen.001"]: THREE.MeshStandardMaterial;
  };
};

export type IphoneType = GLTF & {
  nodes: {
    AbxQOpRbGREHXRG: THREE.Mesh;
    alSOKOYgFKIcUtR: THREE.Mesh;
    FjhETOCBEeiBmch: THREE.Mesh;
    lxsKwuOPNvmzBKg_0: THREE.Mesh;
    tWfjYtMZCfucxRt: THREE.Mesh;
    glass: THREE.Mesh;
    rrqFqyfckTuyRuI: THREE.Mesh;
    XbtrdVaOWYmkEiU: THREE.Mesh;
    aYjPeBrpBRopJbp: THREE.Mesh;
    BeQtuLXtpSTrzAH: THREE.Mesh;
    BDLCJBydsNjizog_0: THREE.Mesh;
    GWEiavWnRxbogtw_0: THREE.Mesh;
    JUTNJcWwqyxbGDZ_0: THREE.Mesh;
    PLFTnNQeqVAxicS: THREE.Mesh;
    RFqaqXLpuCDBIGV_0: THREE.Mesh;
    tWBbDznHihIxXam: THREE.Mesh;
    KUDomTaVduCyevu: THREE.Mesh;
    QaGkMzxNzKPcqRy: THREE.Mesh;
    QOfJIBEXOvXfSUh: THREE.Mesh;
    RUMRNTkptJGDMpy: THREE.Mesh;
    aVmapfDgqkPkjUf: THREE.Mesh;
    CAQeTxdpUcbxQyT: THREE.Mesh;
    lgnGJJmNebyRbHq_0: THREE.Mesh;
    qsTxqfACkdoWeLQ: THREE.Mesh;
    tQCDizUpBYNcvFA: THREE.Mesh;
    zPPSOvNamLQVyvv: THREE.Mesh;
    MoTJNOoMxqdxNvQ: THREE.Mesh;
    mZxrNiCtMrMjOMv: THREE.Mesh;
    YPGjoywokSeoQFr: THREE.Mesh;
    dNDonqESZOxUcei_0: THREE.Mesh;
    IuMgFUHIyRWENxG_0: THREE.Mesh;
    nJYGEbPQybRBbiN: THREE.Mesh;
    RGbIswEcCTzqNsn_0: THREE.Mesh;
    XeFHhVBtRZWPGxR: THREE.Mesh;
    JyAbjubWrOdfygC_0: THREE.Mesh;
    nxFoHsySvfcSLvp: THREE.Mesh;
    oCklTGvTZoDWJrC_0: THREE.Mesh;
    BhvzCWikxrVeDTV: THREE.Mesh;
    DLfIUIalXuQjJsL: THREE.Mesh;
    ePYqawqlCJbCsNi: THREE.Mesh;
    FaUtifOQSMTXiZM: THREE.Mesh;
    FGDSbHbILfUmiaH: THREE.Mesh;
    jQXfQpudiYObSGp: THREE.Mesh;
    KABLQLZRuEbcLWk: THREE.Mesh;
    knexoFNknstHgiO: THREE.Mesh;
    MMkajxMNWrwGQfi: THREE.Mesh;
    OMkeKbwVHRBkBwM: THREE.Mesh;
    qjXEDwnnBYwWcJn: THREE.Mesh;
    YnrVhXEUDbStWCs: THREE.Mesh;
    rJeCWUNsVVXXAbI: THREE.Mesh;
    rqSonbcVVSPWFfa_0: THREE.Mesh;
    vauUojKrKkLLDtY: THREE.Mesh;
    wjSYkRykuFHJNPw: THREE.Mesh;
    yqmgDmvGsmuPwXx_0: THREE.Mesh;
    UCttAeyROPsgmix: THREE.Mesh;
    Screen001: THREE.Mesh;
  };
  materials: {
    IDdMwJVCyuFpUnA: THREE.MeshStandardMaterial;
    sWxYOtHGWTcXRMx: THREE.MeshStandardMaterial;
    KtvhjlxyToKjYkE: THREE.MeshStandardMaterial;
    KhJiSWFcsscOusf: THREE.MeshStandardMaterial;
    fdfRsQCrfvPBPfQ: THREE.MeshStandardMaterial;
    glass: THREE.MeshPhysicalMaterial;
    CSNzlRnZuvCyxNL: THREE.MeshStandardMaterial;
    YiceMpFVTpnmoaq: THREE.MeshStandardMaterial;
    ramColorInside: THREE.MeshStandardMaterial;
    initialShadingGroup: THREE.MeshStandardMaterial;
    fGwijctGaiRaYJC: THREE.MeshStandardMaterial;
    FsunUcGyajFpQmW: THREE.MeshStandardMaterial;
    ramDividerColor: THREE.MeshStandardMaterial;
    BLpVAsLWNICZYGG: THREE.MeshStandardMaterial;
    nJRBoEsOhzMSqCz: THREE.MeshStandardMaterial;
    OStzgRHtVBLWwiD: THREE.MeshStandardMaterial;
    iEhZxWeNLTDdgxm: THREE.MeshStandardMaterial;
    vsSJQngPxBJTVZb: THREE.MeshStandardMaterial;
    sideButtons: THREE.MeshStandardMaterial;
    ramColor: THREE.MeshStandardMaterial;
    mutePhoneColor: THREE.MeshStandardMaterial;
    LtesZnUOMbBEAoi: THREE.MeshStandardMaterial;
    qEGySvwsouNnVcn: THREE.MeshStandardMaterial;
    cameraLensColor: THREE.MeshStandardMaterial;
    LcWBQfBvCzxThpp: THREE.MeshStandardMaterial;
    tDZQoaroJfCIQtF: THREE.MeshStandardMaterial;
    FlDKBWPodPcEeGy: THREE.MeshStandardMaterial;
    tfbCjiZQaZkmtHx: THREE.MeshStandardMaterial;
    back: THREE.MeshStandardMaterial;
    pBMikDFQfUOsKkr: THREE.MeshStandardMaterial;
    IkWzRHNnDaKQXIi: THREE.MeshStandardMaterial;
    EJpkIDZfhPDUzel: THREE.MeshStandardMaterial;
    ["ramColorBack(camera)"]: THREE.MeshStandardMaterial;
    HvAGJeQTAiWbceX: THREE.MeshStandardMaterial;
    KxzouvBYEgdZhMo: THREE.MeshStandardMaterial;
    bmOZLlCkCKhIIVe: THREE.MeshStandardMaterial;
    ["screen.001"]: THREE.MeshStandardMaterial;
  };
};

export type TVType = GLTF & {
  nodes: {
    Object_25: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_31001: THREE.Mesh;
  };
  materials: {
    ["02_-_Default"]: THREE.MeshStandardMaterial;
    ["03_-_Default"]: THREE.MeshStandardMaterial;
    ["04_-_Default"]: THREE.MeshStandardMaterial;
    ["05_-_Default"]: THREE.MeshStandardMaterial;
    main_glass: THREE.MeshPhysicalMaterial;
    ["screen_main.001"]: THREE.MeshStandardMaterial;
  };
};
