import type { Metadata } from "next";
import { Inter, Outfit, Ubuntu } from "next/font/google";

import Nav from "@/ui/components/moleculs/Nav.molecul";
// TRANSLATIONS
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import "./globals.css";
import "@/ui/styles/global.scss";
import { ContextProvider } from "@/ui/providers/ContextProvider.provider";

const inter = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mockify",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <ContextProvider>
      <html lang={locale}>
        <body className={`${inter.className} body`}>
          <NextIntlClientProvider messages={messages}>
            <Nav />
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </ContextProvider>
  );
}
